
language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "anant-pawar-github"
    token:
      secure: $SONAR_TOKEN

services:
  - docker

script:
  - ./mvnw clean jacoco:prepare-agent install -Pci -Dsonar.projectKey=MLS-CS_survey-service  -Dsonar.organization=mls-cs -Dsonar.host.url=https://sonarcloud.io